name: GCards Dev Main Comparison
permissions:
  contents: read
  pull-requests: write

 # Triggers the workflow on all pushes to main and all pull requests
on:
  pull_request:
  merge_group:
  push:
    branches: [ main ]
    tags: [ '*' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Allows this workflow to be called by other workflows
  # Thus the checkout with repository: ${{ 'gemc/clas12Tags' }} is added
  workflow_call:

jobs:
  generate-matrix:
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-fedora36
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    # Skip this entire job if the commit was made by the merge queue bot
    if: github.event.head_commit.committer.name != 'github-merge-queue[bot]'
    steps:
      - name: Creates list of gcards
        uses: actions/checkout@main
        with:
          repository: ${{ 'gemc/clas12Tags' }}
      - id: set-matrix
        run: |
          echo "Current Working Directory: $(pwd)"
          echo "Content: $(ls -l)"
          export JSON=$( ./ci/gcards_dev_main_list.sh )
          echo generate-matrix: $JSON
          echo "matrix=$( echo "$JSON" | tr -d '\n' )" >> $GITHUB_OUTPUT

  compare:
    needs: generate-matrix
    runs-on: ubuntu-latest
    container: jeffersonlab/gemc:dev-almalinux94
    strategy:
      fail-fast: false
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    # Skip this entire job if the commit was made by the merge queue bot
    if: github.event.head_commit.committer.name != 'github-merge-queue[bot]'
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          repository: ${{ 'gemc/clas12Tags' }}
      - name: Build GEMC
        run: |
          ./ci/build_gemc.sh
      - name: Install Software
        run: |
          ./ci/install_comparison_software.sh
      - name: ${{ matrix.gcard }} tests
        run: |
          ./ci/gcard_dev_main_comparison.sh -g ${{ matrix.gcard }}
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: gemclogs-${{ matrix.gcard }}
          path: /root/logs/

  compare-result:
    needs: compare
    runs-on: ubuntu-latest
    # Skip this entire job if the commit was made by the merge queue bot
    if: github.event.head_commit.committer.name != 'github-merge-queue[bot]'
    steps:
      - name: Collect logs
        uses: actions/download-artifact@v4
        with:
          pattern: gemclogs-*
      - name: Detailed Table
        run: |
          ls */*output_details.log
          cat */*output_details.log > comparison.log
          echo "| GCard | Bank | Status  |" > Summary.md
          echo "|-------|---------|---------|" >> Summary.md
          while IFS=: read -r gcard bank pass; do
            echo "| $gcard | $bank | $pass |" >> Summary.md
          done < comparison.log
          cat Summary.md >> $GITHUB_STEP_SUMMARY
      - name: Summary Table
        run: |
          ls */*output_summary.log
          cat */*output_summary.log > comparison.log
          echo "| GCard | Status  |" > Summary.md
          echo "|----------|---------|" >> Summary.md
          while IFS=: read -r gcard pass; do
            echo "| $gcard | $pass |" >> Summary.md
          done < comparison.log
          cat Summary.md >> $GITHUB_STEP_SUMMARY

  compare-result-final:
    needs:
      - compare-result
    runs-on: ubuntu-latest
    # Skip this entire job if the commit was made by the merge queue bot
    if: github.event.head_commit.committer.name != 'github-merge-queue[bot]'
    steps:
      - name: fail
        if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') || contains(needs.*.result, 'skipped') }}
        run: |
          echo "### Some tests failed." >> $GITHUB_STEP_SUMMARY
          exit 1
      - name: pass
        run: |
          echo "### All tests passed." >> $GITHUB_STEP_SUMMARY
          exit 0
